name: Copy Files and Push

on:
  push:
    branches:
      - main

jobs:
  copy_files:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:

      - name: Checkout source repository
        uses: actions/checkout@v2
        with:
          repository: sakethvaliveti1/syncs
          path: syncs
      
      - name: Checkout destination repository
        uses: actions/checkout@v2
        with:
          repository: sakethvaliveti1/syncd
          path: syncd
      
      - name: Copy files to destination repository
        run: |
          find syncs -type f -name 'zxy*' -exec install -D -m 644 -t syncd/def/abc/kpi/ {} \;
          find syncs -type f -name 'abcd*' -exec install -D -m 644 -t syncd/abcd/abc/kpi/ {} \;

      - name: Commit changes and push to destination repository
        uses: EndBug/add-and-commit@v9.1.1
        with:
          cwd: syncd/
          author_name: Saketh Valiveti
          author_email: saketh.valiveti@aver.io
          message: 'Copy files from source-repo to destination-repo'
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
