on:
    push:
        branches:
            - main

name: ⏫ Copy content to dest

jobs:
    copy-file:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            # Copy the 'post' folder
            - name: Push posts
              uses: dmnemec/copy_file_to_another_repo_action@main
              env:
                  API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
              with:
                  source_file: "sfolder/" # Folder to copy
                  destination_repo: "sakethvaliveti1/syncd" # Target repo
                  destination_folder: "dfolder/" # Folder where to copy it
                  user_email: "saketh.valiveti@aver.io"
                  user_name: "sakethvaliveti1"
                  commit_message: "AUTO: Copying posts from Dom's to REBEL's website"
                  git_server: "github.com"
